[versions]
jline = "3.25.1"
aesh-terminal = "3.0"
junit = "5.14.1"
assertj = "3.27.6"
native-build-tools = "0.11.1"
picocli = "4.7.6"
nexus = "2.0.0"
oshi = "6.9.2"
animal-sniffer = "2.0.0"
sniffer18-signature = "1.0"
compile-testing = "0.21.0"
gradle-tooling-api = "9.2.1"
asciidoctor = "4.0.4"
git-publish = "3.0.1"
spotless = "8.2.1"
apache-sshd = "3.0.0"
netty = "4.1.81.Final"

[libraries]
jline = { module = "org.jline:jline", version.ref = "jline" }
aesh-terminal = { module = "org.aesh:terminal-tty", version.ref = "aesh-terminal" }
aesh-terminal-ssh = { module = "org.aesh:terminal-ssh", version.ref = "aesh-terminal" }
aesh-terminal-http = { module = "org.aesh:terminal-http", version.ref = "aesh-terminal" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
graalvm-native = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref = "native-build-tools" }
nexus-publishing-plugin = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus" }
animal-sniffer-plugin = { module = "ru.vyarus:gradle-animalsniffer-plugin", version.ref = "animal-sniffer" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }
sniffer18-signature = { module = "org.codehaus.mojo.signature:java18", version.ref = "sniffer18-signature" }
compile-testing = { module = "com.google.testing.compile:compile-testing", version.ref = "compile-testing" }
gradle-tooling-api = { module = "org.gradle:gradle-tooling-api", version.ref = "gradle-tooling-api" }
asciidoctor-plugin = { module = "org.asciidoctor:asciidoctor-gradle-jvm", version.ref = "asciidoctor" }
git-publish-plugin = { module = "org.ajoberstar.git-publish:org.ajoberstar.git-publish.gradle.plugin", version.ref = "git-publish" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
apache-sshd-core = { module = "org.apache.sshd:sshd-core", version.ref = "apache-sshd" }
apache-sshd-netty = { module = "org.apache.sshd:sshd-netty", version.ref = "apache-sshd" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }

[bundles]
testing = ["junit-jupiter", "junit-platform-launcher", "assertj-core"]

[plugins]
animal-sniffer = { id = "ru.vyarus.animalsniffer", version.ref = "animal-sniffer" }
