name: ci-build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: &inputs
      debug_enabled:
        description: 'Run the build with upterm debugging enabled (https://github.com/owenthereal/action-upterm)'
        required: false
        type: boolean
        default: false

jobs:
  format-check:
    name: Static Code Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: ./.github/actions/shared-build-setup
      - name: check formatting and comment on PR if failed
        id: check-formatting
        run: ./gradlew spotlessCheck
  jbang-catalog-check:
    name: Verify JBang Demos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/shared-build-setup
      - name: Update jbang-catalog.json to include new demos
        run: |
          ./gradlew publishToMavenLocal
          ./gradlew updateJBangCatalog --verify-builds --parallel

      - name: Check jbang-catalog.json is up to date
        run: |
          if ! git diff --exit-code -- jbang-catalog.json; then
            echo "::error file=jbang-catalog.json::jbang-catalog.json is out of sync. Please run './gradlew updateJBangCatalog --verify-builds' and commit the changes."
            exit 1
          fi
  build:
    name: Full Gradle Build (excluding distributions)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/shared-build-setup

      - name: Execute Gradle
        run: ./gradlew build -x spotlessCheck -x distTar -x distZip